class Allyas < Formula
  desc "Personal shell aliases for macOS"
  homepage "https://github.com/rezkam/allyas"
  url "https://github.com/rezkam/allyas/archive/refs/tags/v0.0.2.tar.gz"
  sha256 "a9322c20a6ed20b4a066b327c8ecddfa6be87f50d0f2e184318db6d0729b0fd5" # Will be auto-generated by GitHub Actions from source repo
  version "0.0.2"
  license "MIT"

  def install
    # Keep a copy inside the Cellar
    pkgshare.install "allyas.sh"
    # Provide a convenient symlink under etc for sourcing
    etc.install_symlink pkgshare/"allyas.sh"
  end

  def caveats
    shell = File.basename(ENV.fetch("SHELL", ""))
    config_line = "[ -f $(brew --prefix)/etc/allyas.sh ] && . $(brew --prefix)/etc/allyas.sh"

    config_file, reload_cmd, one_liner, restart_cmd =
      case shell
      when "zsh"
        ["~/.zshrc", "source ~/.zshrc", "echo '#{config_line}' >> ~/.zshrc && source ~/.zshrc", "exec zsh -l"]
      when "bash"
        ["~/.bashrc (or ~/.bash_profile)", "source ~/.bashrc", "echo '#{config_line}' >> ~/.bashrc && source ~/.bashrc", "exec bash -l"]
      else
        ["your shell profile", "restart your shell", nil, "restart your shell session"]
      end

    oh_my_zsh_note =
      if shell == "zsh"
        <<~OHMYZSH
          🧩 Using Oh My Zsh? Remove the built-in git plugin to avoid alias conflicts:
            # Open ~/.zshrc, find the line that looks like: plugins=(git ...).
            # Remove `git` from that list, save the file, then restart zsh:
            exec zsh -l
        OHMYZSH
      else
        ""
      end

    <<~EOS
      🎉 allyas has been installed!

      Detected shell: #{shell.empty? ? "unknown" : shell}

      Add this line to #{config_file}:
        #{config_line}

      #{one_liner ? "Run this to append & reload now:\n        #{one_liner}\n" : ""}

      Then reload your shell:
        #{reload_cmd}

      To fully restart your shell:
        #{restart_cmd}

      #{oh_my_zsh_note}

      To verify installation:
        ls -la $(brew --prefix)/etc/allyas.sh

      To update your aliases:
        brew update && brew upgrade allyas
    EOS
  end

  test do
    # Verify that the aliases file and symlink were installed
    assert_predicate pkgshare/"allyas.sh", :exist?
    assert_predicate etc/"allyas.sh", :exist?
    assert_match "allyas", (pkgshare/"allyas.sh").read
  end
end
