class Allyas < Formula
  desc "Personal shell aliases for macOS"
  homepage "https://github.com/rezkam/allyas"
  url "https://github.com/rezkam/allyas/archive/refs/tags/v0.0.1.tar.gz"
  sha256 "d0662145860f9c99d3b75c4b893e233bb305e4f7d13596a06a8cf147d0e7b2cb" # Will be auto-generated by GitHub Actions from source repo
  version "0.0.1"
  license "MIT"

  def install
    # Keep a copy inside the Cellar
    pkgshare.install "allyas.sh"
    # Provide a convenient symlink under etc for sourcing
    etc.install_symlink pkgshare/"allyas.sh"
  end

  def caveats
    <<~EOS
      🎉 allyas has been installed!

      To use these aliases, add this line to your shell configuration:

      For bash (~/.bashrc or ~/.bash_profile):
        [ -f $(brew --prefix)/etc/allyas.sh ] && . $(brew --prefix)/etc/allyas.sh

      For zsh (~/.zshrc):
        [ -f $(brew --prefix)/etc/allyas.sh ] && . $(brew --prefix)/etc/allyas.sh

      Then reload your shell:
        source ~/.zshrc    # for zsh
        source ~/.bashrc   # for bash

      To verify installation:
        ls -la $(brew --prefix)/etc/allyas.sh

      To update your aliases:
        brew update && brew upgrade allyas
    EOS
  end

  test do
    # Verify that the aliases file and symlink were installed
    assert_predicate pkgshare/"allyas.sh", :exist?
    assert_predicate etc/"allyas.sh", :exist?
    assert_match "allyas", (pkgshare/"allyas.sh").read
  end
end
